galaxy_info:
  author: Fedor Molokov
  description: Preconfig script for deploy gitlab into the cluster
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: CentOS
      versions:
        - 8
dependencies: []
