---
- name: Preconfig nodes
  hosts: k3s_cluster
  vars:
    k3s_become_for_all: true
  roles:
    - role: preconfig
    # - role: docker-install
    # - role: codecap.kubectl
      # become: true
    - role: xanmanning.k3s
      become: true
    - role: k3s-config-permission
    # - role: end