apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-argo-application
  namespace: argocd
spec:
  project: p3

  source:
    repoURL: https://github.com/Fedor-Molokov/IoT.git
    targetRevision: HEAD
    path: p3/confs/changeable/apps
  destination: 
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=false

    automated:
      selfHeal: true
      prune: true
