---
- name: Test k3d
  ansible.builtin.shell: k3d cluster list
  ignore_errors: True

- name: Create k3d cluster
  command: k3d cluster create cluster --k3s-arg "--disable=traefik@server:0" -p "80:80@loadbalancer" -p "443:443@loadbalancer"
  ignore_errors: True

- name: Create k3d cluster
  shell: k3d cluster create cluster --k3s-arg "--disable=traefik@server:0" -p "80:80@loadbalancer" -p "443:443@loadbalancer"
  ignore_errors: True

- name: Create k3d cluster
  ansible.builtin.shell: k3d cluster create cluster --k3s-arg "--disable=traefik@server:0" -p "80:80@loadbalancer" -p "443:443@loadbalancer"
#   register: result
#   ignore_errors: True

# - name: fail the play if the previous command did not succeed
#   fail: msg=result.stderr
#   when: "'\u001b[31mFATA\u001b[0m[0000] Failed to create cluster 'IoTCluster' because a cluster with that name already exists' not in result.stderr"