galaxy_info:
  author: Fedor Molokov
  description: deploy kubernetes resources
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: CentOS
      versions:
        - 8
  dependencies:
    - role: preconfig
    - role: k3s-config-permission