apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: npuzzle-app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    # ************************** #
    # For deploy gitlab into cluster
    #
    # repoURL: https://10.0.2.2:8080/root/gitlab.git
    # ************************** #
    targetRevision: HEAD
    path: ./
  destination: 
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=false

    automated:
      selfHeal: true
      prune: true
