---
- name: Preconfig nodes
  hosts: k3s_cluster
  roles:
    - role: preconfig

- name: Build a cluster with a single control node
  hosts: master
  roles:
    - role: config-master-node

- name: Build a cluster with a single control node
  hosts: worker
  roles:
    - role: config-worker-node